### ISSUE TITLE
Use Tinker's event instead of overriding existing materials

### ISSUE THREAD

**Issue by LemADEC** [Davoleo/Metallurgy-4-Reforged#158]
**Describe the bug**
Game crash on load when stats are already defined in Tinker's Construct, advising to use events insteads.

**To Reproduce**
Start the game

**Expected behavior**
Games boot

**Versions:**
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2838
- Minecraft: 1.12.2
- Conflicting mod: Tinker's Construct API
- Other mods you think could cause issues:  
  - Mantle 1.12-1.3.3.55
  - Tinker's Construct 1.12.2-2.12.0.135
  - Construct Armory 1.12.2-1.2.3.4
  - MMDLib 1.12-1.0.0-rc2.36
  - BaseMetals 1.12-2.5.0-rc2.332
  - OreSpawn 1.12-3.3.1.172

**Crash Report**
https://gist.github.com/LemADEC/7e371f8d66bae637c925b197304380f9
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Metallurgy 4: Reforged (metallurgy)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Stats to "adamantine": Stats of type "core" were already registered by MMDLib. Use the events to modify stats.
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:232)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:208)
	at it.hurts.metallurgy_reforged.integration.mods.IntegrationCArmory.preInit(IntegrationCArmory.java:36)
	at it.hurts.metallurgy_reforged.Metallurgy.preInit(Metallurgy.java:91)
```

**Comment by HurtsAsHell** [comment]
The problem is the conarm and it will fix in the next release
