### ISSUE TITLE
Pewter mod crash

### ISSUE THREAD

**Issue by TBiscuit1** [Davoleo/Metallurgy-4-Reforged#192]
When the mod is with pewter, the game crash

To reproduce the bug you just need metallurgy + pewter

Versions:
- Metallurgy 4: Reforged: Any
- Conflicting mod : Pewter
- The osmium is the problem
Crash Report :
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  MekanismCoremod (Mekanism-1.12.2-9.7.9.380.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/19/19 7:24 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pewter (pewter)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "osmium": It was already registered by Metallurgy 4: Reforged
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:986)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:131)
	at slimeknights.tconstruct.library.MaterialIntegration.preInit(MaterialIntegration.java:101)
	at com.ejektaflex.pewter.logic.MaterialRegistrar.preIntegrateMaterial(MaterialRegistrar.kt:191)
	at com.ejektaflex.pewter.logic.MaterialRegistrar.preInit(MaterialRegistrar.kt:47)
	at com.ejektaflex.pewter.proxy.CommonProxy.preInit(CommonProxy.kt:30)
	at com.ejektaflex.pewter.proxy.ClientProxy.preInit(ClientProxy.kt:32)
	at com.ejektaflex.pewter.Pewter.preInit(Pewter.kt:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 908622600 bytes (866 MB) / 1173880832 bytes (1119 MB) up to 5965348864 bytes (5689 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6400m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version           | Source                                  | Signature                                |
	|:----- |:------------------ |:----------------- |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2            | minecraft.jar                           | None                                     |
	| LCH   | mcp                | 9.42              | minecraft.jar                           | None                                     |
	| LCH   | FML                | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forgelin           | 1.8.3             | Forgelin-1.8.3.jar                      | None                                     |
	| LCH   | mantle             | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                | None                                     |
	| LCH   | metallurgy         | 0.2.2             | Metallurgy-4-Reforged-0.2.2.jar         | None                                     |
	| LCH   | mekanism           | 1.12.2-9.7.9.380  | Mekanism-1.12.2-9.7.9.380.jar           | None                                     |
	| LCH   | mekanismgenerators | 1.12.2-9.7.9.380  | MekanismGenerators-1.12.2-9.7.9.380.jar | None                                     |
	| LCH   | tconstruct         | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar        | None                                     |
	| LCE   | pewter             | 1.4.3             | Pewter-1.4.3.jar                        | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.7.9.380.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.71' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

**Comment by TBiscuit1** [comment]
Found what is the problem! It's the tinker material that made the crash! I turn off the tinker integration and the game don't crash!

**Comment by HurtsAsHell** [comment]
I need that you use the bug guideline 
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 
- Forge: 
- Minecraft:
- Modpack _(if available)_:
- Conflicting mod _(if regarding mod integration)_:
- Other mods you think could cause issues:  

**Crash Report** _(if available)_
**Use [gist](https://gist.github.com) or spoilers or [paste.ee](https://paste.ee) or [pastebin](https://pastebin.com)**

**Log** _(latest.log)_ 
**Use [gist](https://gist.github.com) or spoilers or [paste.ee](https://paste.ee) or [pastebin](https://pastebin.com)**

**Additional context** _(if needed)_
Add any other context about the problem here.
```

**Comment by HurtsAsHell** [comment]
Use the guideline and i will check the crashlog / lateslog

**Comment by TBiscuit1** [comment]
Are you kiding me?! SERIOUSLY

**Comment by HurtsAsHell** [comment]
Use [gist](https://gist.github.com) or spoilers or [paste.ee](https://paste.ee) or [pastebin](https://pastebin.com)**

Yes because I can't lose an hour to read badly indented lines.

**Comment by SashaIndustries** [comment]
Having the same problem so perhaps two people instead of one will be worth more time.
Also that text is only the error log not the whole startup phase and session.
I read it and I'm not even the one who made the mod, google directed me here after searching about the conflict with Osmium

**Comment by Handeril** [comment]
Please check [Modpack/Minecraft Directory]/config/metallurgy_reforged/general.cfg

In that file, there should be a category appearing as the following:

# Add a material in this array to blacklist it during game boot - material name format is "snake_case" (e.g. 'osmium' or 'damascus_steel')
    S:"Tinker Materials Blacklist" <
     >

Add "osmium" to the Blacklist in either Pewter OR Metallurgy 4: Reforged in order to resolve the crash.

If you have TAIGA installed as well, add Prometheum to the blacklist as well. [Gameplay-effecting bug]

**Comment by Davoleo** [comment]
ah right, yes you can also fix that way, but I'll still add the patch I was talking about in the new issue

**Comment by SashaIndustries** [comment]
Oh had no idea the project had changed owners haha. Also exciting to see it improving, thank you for the reply and also for continuing the project! Sorry if I came across hostile at all just was saddend to see someone ignored who actively tried to help. Had things I made in the past but they never took off so couldn't find anyone at the time to test my things so was perhaps a bit personal for me. But thank you for the quick reply and its great to be able to have more mods working together :)

**Comment by ASideWinder** [comment]
hello,

sorry for necroposting, but my issue is similar, if not identical to a small detail: the troubles come from MMDLib registering antimony

the solution above was to blacklist the material, but it doesn't seem to take effect on the MMDLib .cfg file

if my issue requires a new request, i understand, just let me know

**Comment by Davoleo** [comment]
@ASideWinder 
we don't have any material called `antimony` in metallurgy, so it's probably a conflict with another mod.

in any case check out #335 
there is a configuration file in metallurgy that allows you to disable certain materials from registering TiCon compat.
